#include "LED.h"
#include"GPIO.h"

void LEDS_init(void)
{
	GPIO_setupPinDirection(LED_RED_PORT_ID, LED_RED_PIN_ID, PIN_OUTPUT);
	GPIO_setupPinDirection(LED_GREEN_PORT_ID, LED_GREEN_PIN_ID, PIN_OUTPUT);
	GPIO_setupPinDirection(LED_BLUE_PORT_ID, LED_BLUE_PIN_ID, PIN_OUTPUT);

	GPIO_writePin(LED_RED_PORT_ID, LED_RED_PIN_ID, LED_ON);
	GPIO_writePin(LED_GREEN_PORT_ID, LED_GREEN_PIN_ID, LED_ON);
	GPIO_writePin(LED_BLUE_PORT_ID, LED_BLUE_PIN_ID, LED_ON);

#if(CONNECTION_TYPE == POSITIVE_LOGIC)
	GPIO_writePin(LED_RED_PORT_ID, LED_RED_PIN_ID,LOGIC_LOW);
	GPIO_writePin(LED_RED_PORT_ID, LED_GREEN_PIN_ID,LOGIC_LOW);
	GPIO_writePin(LED_RED_PORT_ID, LED_BLUE_PIN_ID,LOGIC_LOW);


#elif(CONNECTION_TYPE == NEGATIVE_LOGIC)
	GPIO_writePin(LED_RED_PORT_ID, LED_RED_PIN_ID,LOGIC_LOW);
	GPIO_writePin(LED_RED_PORT_ID, LED_GRN_PIN_ID,LOGIC_LOW);
	GPIO_writePin(LED_RED_PORT_ID, LED_BLU_PIN_ID,LOGIC_LOW);

#endif
}


void LED_on(LED_ID id)
{
#if(CONNECTION_TYPE == POSITIVE_LOGIC)
	GPIO_writePin(PORTC_ID, id, LOGIC_HIGH);

#elif(CONNECTION_TYPE == NEGATIVE_LOGIC)
	GPIO_writePin(LEDS_PORT_ID, id, LOGIC_LOW);

#endif
}


void LED_off(LED_ID id)
{
#if(CONNECTION_TYPE == POSITIVE_LOGIC)
	GPIO_writePin(PORTC_ID, id, LOGIC_LOW);

#elif(CONNECTION_TYPE == NEGATIVE_LOGIC)
	GPIO_writePin(LEDS_PORT_ID, id, LOGIC_HIGH);

#endif
}
